### ISSUE TITLE
Chart not properly displayed

### ISSUE THREAD

**Issue by beJustAwsome** [PierreMarion23/pivot-table-widget#7]
Hi,

I would like to ask regarding the alignment of chart. It seems that the x-axis and labels are not properly displayed. Please see the screenshot. How to fix this.? Thanks :) 

![image](https://user-images.githubusercontent.com/29233252/37298136-7cdae3dc-265a-11e8-96d1-47752d38f869.png)
![image](https://user-images.githubusercontent.com/29233252/37298228-b7e8e91a-265a-11e8-85bf-57e119bada95.png)
![image](https://user-images.githubusercontent.com/29233252/37298295-d7e2dd84-265a-11e8-8d78-74fcde905314.png)

**Comment by PierreMarion23** [comment]
Hello,
I am not sure to exactly understand what the problem is: what would you like to display instead of what is in the screenshot?
Anyway, concerning the display of the plots, we did not work on it, but only call the library [PivotTable.js](https://github.com/nicolaskruchten/pivottable) developped by [Nicolas Kruchten](https://github.com/nicolaskruchten/). So if your issue is with the display, you should contact him :).
Pierre
